version: '3'


services:

  rabbitmq1:
    image: rabbitmq:management-alpine
    restart: always
    hostname: rabbitmq1
    volumes:
      - ./data:/var/lib/rabbitmq
    environment:
      - RABBITMQ_ERLANG_COOKIE=${RABBITMQ_ERLANG_COOKIE}
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
      - RABBITMQ_DEFAULT_VHOST=${RABBITMQ_DEFAULT_VHOST}
    ports:
      - "4369:4369"
      - "1883:1883"
      - "25672:25672"

  haproxy:
    image: haproxy:alpine
    restart: always
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    depends_on:
      - rabbitmq1
    ports:
      - 15672:15672
      - 5672:5672
      - 1936:1936
    extra_hosts:
      - "rabbitmq2:${RABBITMQ_MEMBER}"
