version: "2.4"
services:
  rabbitmqMember:
    cpus: ${CPUS} 
    image: rabbitmq:3.7.17-management-alpine
    restart: always
    hostname: ${RABBITMQ_HOSTNAME}
    environment:
      - RABBITMQ_ERLANG_COOKIE=${RABBITMQ_ERLANG_COOKIE}
    volumes:
      - ./data:/var/lib/rabbitmq
      - ./cluster-entrypoint.sh:/usr/local/bin/cluster-entrypoint.sh
    entrypoint: /usr/local/bin/cluster-entrypoint.sh
    extra_hosts:
      - "rabbitmq1:${RABBITMQ_MASTER}"
    ports:
      - "5672:5672"
      - "15672:15672"
      - "4369:4369"
      - "1883:1883"
      - "25672:25672"

