version: "2.4"
services:
  rabbitmq2:
    cpus: ${CPUS} 
    image: rabbitmq:management-alpine
    restart: always
    hostname: rabbitmq2
    environment:
      - RABBITMQ_ERLANG_COOKIE=${RABBITMQ_ERLANG_COOKIE}
    volumes:
      - ./data:/var/lib/rabbitmq
      - ./cluster-entrypoint.sh:/usr/local/bin/cluster-entrypoint.sh
    entrypoint: /usr/local/bin/cluster-entrypoint.sh
    extra_hosts:
          - "rabbitmq1:${RABBITMQ_SERVER}"
    ports:
      - "5672:5672"
      - "15672:15672"
      - "4369:4369"
      - "1883:1883"
      - "25672:25672"

