version: '3'

services:

  rabbitmq2:
    image: rabbitmq:3-management
    hostname: rabbitmq2
    environment:
      - RABBITMQ_ERLANG_COOKIE=${RABBITMQ_ERLANG_COOKIE}
      - CLUSTERED=true
      - CLUSTER_WITH=rabbit@rabbitmq1
    extra_hosts:
          - "rabbitmq1:${RABBITMQ_SERVER}"
    ports:
      - "5672:5672"
      - "15672:15672"
      - "4369:4369"
      - "1883:1883"
      - "25672:25672"

